### PR TITLE
Improve timezone input

### PR DESCRIPTION
**Pull request by st0012**
Hi~ I added default time_zones configuration, updated documentation and some tests.

### CODE REVIEW

**Comment by st0012** [comment]
@mikz Do you have any thought about this PR?

**Comment by mikz** [comment]
@st0012 I'm not much a fan of adding a global configuration for input specific thing.

Would it make sense for you to create a custom input instead?

**Comment by st0012** [comment]
I added the global configuration because I see the `Add config` todo. And there already is the `priority_zones` option to set priority zone per input, so I think the `Add config` means global configuration.

**Comment by mikz** [comment]
@st0012 there are already `priority_countries` in the configuration, so to be consistent it makes sense to add this!

**Comment by st0012** [comment]
@mikz ok, thanks for reviewing!

**Comment by justinfrench** [comment]
Looks good, looks consistent, looks backwards compatible! Merging, thanks!

**Comment by st0012** [comment]
:smile:

**Pull request merged**
