### PR TITLE
Remove Rails 3 and 4.0 Support

### LINKED ISSUE #1105: Remove Formtastic::Deprecation support for Rails 3.2
See `@todo` in `lib/formtastic/deprecation.rb`.

### PR DESCRIPTION
**Pull request by justinfrench**
This is targeted for a merge into `4.0-dev`, which is where we're starting with on 4.0 alongside 3.2 in `master`.

Fixes #1105

### CODE REVIEW

**Comment by mikz** [comment]
@justinfrench I'd really like to get this going. 

Do you think it is safe to drop both rails 3 and 4.0 in one release?

**Comment by justinfrench** [comment]
I think releasing and communicating and upgrading software takes time, so if there's a bunch of big changes, might as well bundle them.

**Comment by mikz** [comment]
@justinfrench so, release another `3.1` release and then continue on `4.0` ? Which would drop support for Rails 3.2 and 4.0 ?
I'd drop support for 4.0 only if it is necessary. 

And include https://github.com/justinfrench/formtastic/pull/1139 in the `4.0` release ?

How can I help?

**Comment by justinfrench** [comment]
@mikz It's tough for me to load all this context back into my brain right now, but yeah, I think we have two main branches to be concerned with:

* 3.1-stable (should be close to master)
* 4.0-dev

Work like this can merge into 4.0-dev when it's ready (this PR wants to merge to 4.0-dev, not master). 3.1.x patches can merge into master, which we should feel safe to release whenever.

I think after the next 3.x release we should end active development on 3.x and focus on a 4.x rc, at which point we'd merge 4.0-dev into master, and the 3.1-stable would only exist for big fixes if required.

If you want to help, here's roughly what I think needs to be done. Perhaps we can track all of it in a new issue?

The goal should be to wrap-up 3.x work ASAP, shift 4.0 beta work to master, ship a beta and an rc.

1. Check that unreleased changes between 3.1-stable and master are releasable as a 3.1.
2. Check that 3.1-stable has deprecation warnings for old Rails versions we plan to kill in 4.0
3. Prepare the next 3.1 release (change logs, tagging, etc see RELEASE_PROCESS
4. Actually push the new 3.x gem (at the moment that's only me that can do it, but I'd be comfortable adding you)
5. Merge 4.0-dev into master and add a link to the 3.1-stable README from master
6. Merge as much 4.0 stuff into master as possible, release a beta gem
7. Create a 4.0 milestone to track issues
8. Ship an 4.0 rc

In regards to #1139 and any other merge-ready open PRs, I'd be happy for you to decide if they're suitable for 3.x or 4.x. My default preference would be defer to 4.0 unless it's a backwards compatible bug fix.

I'm very comfortable aggressively removing old Rails versions in 4.0, as the 3.1 has been very stable and it's the most widely used version ever.

If you feel like opening an issue or two to track this stuff and actively working towards any of it, that'd be awesome. If not, eventually I'll get there :)

**Comment by mikz** [comment]
Great! Will try to do preparations for another 3.1 release tomorrow and prepare issue(s) for the next steps.

**Comment by mikz** [comment]
So I made a PR with the preparations including the CHANGELOG. https://github.com/justinfrench/formtastic/pull/1194
I'd say there are no breaking changes and it can be merged as it is. 

Also, from what I see, it correctly deprecates rails <= 4.0.

**Comment by mikz** [comment]
I did not mean to close this. And I can't reopen it :(

**Comment by mikz** [comment]
Created https://github.com/justinfrench/formtastic/issues/1198 and https://github.com/justinfrench/formtastic/issues/1197 to track the progress.

**Comment by mikz** [comment]
@justinfrench I think this is good to be merged. Wdyt?

**Comment by justinfrench** [comment]
@mikz other than the build fail (which I haven't investigated), I think this is fine to merge. Can you spot anything obvious in the build?

**Comment by mikz** [comment]
@justinfrench it is because of ruby 1.9.3. It is fixed in master (#1195). Will merge master to 4.0-dev after PRs pointing there are merged to prevent conflicts in them.

**Pull request merged**
