### PR TITLE
Support Inet database field types

### PR DESCRIPTION
**Pull request by danielricecodes**
Seems people want this.  See #1146 and #1115.  Also, this [ActiveAdmin issue](https://github.com/activeadmin/activeadmin/issues/4178).

### CODE REVIEW

**Comment by mikz** [comment]
I believe this is not the correct approach to solve this. There is no reason for this class, as it has no implementation.

The problem is that some code defaults to `column.type`, which is not correct in most cases.

https://github.com/justinfrench/formtastic/blob/2f8b987ee4880c4aa06e6ec799eafe48fa46e316/lib/formtastic/helpers/input_helper.rb#L291

We would have to define some mapping, default or something. But defining a class for every column type we want to alias is not the way to go.

**Comment by danielricecodes** [comment]
Are you suggesting to add an inet switch like this?

```ruby
when :inet
  return :string
```

**Comment by mikz** [comment]
Yes. And appropriate test that verifies what it does.

**Comment by danielricecodes** [comment]
@mikz - simple enough.  Sorry about that empty commit, let me know if you want me to remove https://github.com/justinfrench/formtastic/pull/1276/commits/7a3649e04728ac6864cebd2b373f01a38d057bd6

**Comment by danielricecodes** [comment]
@mikz - I am not sure whats going on with Travis but it appears the build is broken.  My change didn't cause it.  I can run RSpec and get 100% passing on my local system.  Ruby MRI 2.6.1 w/ RVM.  

screenshot from 2019-02-15 14-56-06

**Pull request merged**
