### PR TITLE
Remove invalid reference to LabelHelper

### PR DESCRIPTION
**Pull request by markedmondson**
There is no such label_helper

### CODE REVIEW

**Comment by markedmondson** [comment]
Actually, it'd be awesome to have a LabelHelper that doesn't just pass to the default FormBuilder to be able to do something like:

   f.label :datetime
   f.input :datetime_date, label: false
   f.input :datetime_time, label: false

In the case where there's wrapping around the input, then the output can be customized to wrap two inputs with one label.

**Comment by justinfrench** [comment]
@markedmondson I'd need to see some code, so feel free to create an issue or rough-out the beginnings of a PR. Have merged this one, thanks.

**Comment by markedmondson** [comment]
I have working code: https://github.com/justinfrench/formtastic/compare/master...Guestfolio:label-helper?expand=1

However I can't get the tests to run, making it tough to add my own.. any ideas? Segmentation fault right after:

    >> BUNDLE_GEMFILE=/Users/markedmondson/Sites/formtastic/gemfiles/rails_3.2.gemfile bundle exec rake

    /Library/Ruby/Gems/2.0.0/gems/json-1.8.3/lib/json/ext/parser.bundle: [BUG] Segmentation fault at 0x00000000000418
    ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]

**Comment by justinfrench** [comment]
@markedmondson no ideas on the segfault, but if you pseudo-code a test scenario and _start_ a PR, I'd be happy to help polish it off — I'm just not comfortable _starting_ or _defining the goals_ the tests for code I didn't write.

**Pull request merged**
