### PR TITLE
Added hstore input.

### PR DESCRIPTION
**Pull request by ryanfox1985**
Hi,
I added Hstore input.
Regards.

### CODE REVIEW

**Comment by mikz** [comment]
This is exact copy of TextInput no? Then you can do `f.input :hstore, as: :text` and you are good.

**Comment by justinfrench** [comment]
@ryanfox1985 what problem are you trying to solve with this patch? What will Formtastic users be able to do better now that this has been added? I'll close if I haven't heard back in a while, but would love to hear from you.

**Comment by mikz** [comment]
This would not be needed, if Formtastic would just default to string (#1146), right?

**Comment by justinfrench** [comment]
@mikz This is proposing something close to (or exactly like) a `TextInput` (which makes sense to me). If we defaulted to `StringInput` as in #1146, you'd end up with a tiny text field instead if a text area.

I have no thoughts on how/when/where a hstore input is useful (@ryanfox1985, can you tell us more about your use case?), but if it is, this would would make sense to merge regardless of what happens in #1146.

@ryanfox1985 if this *is* a direct copy of the `TextInput` implementation perhaps consider subclassing instead so that they don't accidentally diverge over time?

**Comment by mikz** [comment]
@justinfrench sure. I was more thinking why is this proposing it. Imo there is no way of map columns to inputs globally. If there would be a way to map `:hstore` to `:text` in form builder settings, this PR would not be needed. 

And to me looks like this is exact copy of text input. So rather than copying/subclassing it, it should be adding line to the column to input mapping in [`default_input_type`](https://github.com/justinfrench/formtastic/blob/11b22d0c770cd6d734fb637189d666def56f166e/lib/formtastic/helpers/input_helper.rb#L257) method.

Anyway, we should hear what @ryanfox1985 tried to accomplish with this, so we can decide if it is the right way to do it or there are better things to do.

**Comment by ryanfox1985** [comment]
Hi,

Sorry but when I created the PR I didn't know that you can render the
hstore fields as text input.

Regards.

**Pull request closed without merging**
