### PR TITLE
Integer instead of Fixnum for Ruby 2.4

### PR DESCRIPTION
**Pull request by matthewrudy**

### CODE REVIEW

**Comment by mikz** [comment]
Would be good to have a test failure for this one. Maybe adding ruby 2.4 to travis would be enough to get it failing?

**Comment by matthewrudy** [comment]
hey @mikz I did do that bit
but didn't resolve the nokogiri / ruby version issues.

i guess that's a general issue for master too though.

**Comment by mikz** [comment]
master build fixed by https://github.com/justinfrench/formtastic/pull/1236
could you rebase and see?

**Comment by matthewrudy** [comment]
@mikz rebased and it looks good.

Notably, there are still deprecation warnings from `activesupport` (will be fixed in rails 5.0.2) and `diff-lcs` (not likely to be fixed any time soon.

**Comment by mikz** [comment]
Thank you!

**Pull request merged**
