### PR TITLE
Remove deprecated finder methods

### LINKED ISSUE #1104: Remove support for deprecated 3.0 custom class methods
3.1.0 added new configurations for custom class finders with namespacing, and deprecated the old methods that some other libraries were subclassing (`input_class`, `custom_input_class_name`, `standard_input_class_name`, `action_class`, `custom_action_class_name`, `standard_action_class_name`, `input_class_by_trying`, etc). Pretty much anything with the `@deprecated` tag right now.

Any chance you're keen on this @mikz? It's probably about time I add you as a collaborator if you're keen?

### LINKED ISSUE #1106: Default to new `input_class_finder` and `action_class_finder`
See `@todo`s in `form_builder.rb`.

### LINKED ISSUE #1107: Clean-up action_helper_spec.rb
This…

```
include_context 'Action Helper' # from spec/support/shared_examples.rb
```

points to…

```
# TODO: move this back to spec/helpers/action_helper_spec.rb in Formtastic 4.0
```

I also noticed:

```
# TODO: remove this in Formtastic 4.0
  describe 'instantiating an action class' do
    # ...
  end
```

### PR DESCRIPTION
**Pull request by mikz**
* cleans up specs
* removed plenty of deprecation warnings
* new installs will get default from formtastic form builder
* merges split tests (via shared contexts) and uses default class finder there

closes #1104
closes #1106
closes #1107

needs:

- [x] wiki page describing the input finders

### CODE REVIEW

**Comment by mikz** [comment]
@justinfrench it contains the diff between `master` and `4.0-dev`.
Are you sure there will be some releases of `3.x` ? Because otherwise we could have `3.1-stable` for 3.1.x and `master` pointing to 4.0.

**Comment by justinfrench** [comment]
@mikz I don't think there'll be a 3.2 or 3.3, but I _prefer_ we switch master to track our 4.x development after the RCs and/or Betas (4.0.0 has been released).

**Comment by mikz** [comment]
@justinfrench ok! Will adjust the plan in #1197

**Comment by justinfrench** [comment]
@mikz I actually don't care too much — if you already have a nice plan, roll with it :)

**Comment by mikz** [comment]
@justinfrench my only point for using master is that is is the default branch and people could open PRs that would be not mergeable afterwards. We could also change the default branch to `4.0-dev` temporarily.

**Comment by justinfrench** [comment]
@mikz you're right, let's just go with master

**Comment by mikz** [comment]
@justinfrench I think this is good to go into `4.0-dev`. The spec changes are just copying part of a file to another file.

**Comment by justinfrench** [comment]
:+1:

**Pull request merged**
