### PR TITLE
Change readme to markdown.

### PR DESCRIPTION
**Pull request by st0012**
@justinfrench @mikz Should I change hash syntax too?

### CODE REVIEW

**Comment by justinfrench** [comment]
The hash syntax is in lots of other documentation, so I'd keep the focus here on just the document format, not content changes, then follow up with another PR.

**Comment by justinfrench** [comment]
What are you going to do with `README.textile` before this merges?

**Comment by st0012** [comment]
I am not sure, do you want to delete it?

**Comment by justinfrench** [comment]
It could be deleted, but lots of stuff probably links to it. I guess delete the contents of `README.textile` and provide a link or instructions to `README.md` instead?

**Comment by st0012** [comment]
@justinfrench done.

**Comment by justinfrench** [comment]
Merged, thanks!

**Comment by st0012** [comment]
Happy to help :smile:

**Pull request merged**
