### PR TITLE
Backport Ruby 2.4 support to 3.1 stable

### PR DESCRIPTION
**Pull request by mikz**
Integer instead of Fixnum for Ruby 2.4

closes https://github.com/justinfrench/formtastic/issues/1243

@justinfrench I'll need you to push the release to rubygems. I can prepare the version bump, but I don't have push rights to rubygems.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
@mikz Are you privately in touch with @justinfrench or is he really inactive since September like it seems from his GitHub profile? Or in other words, can we expect this to move forward any time soon?

**Comment by mikz** [comment]
@deivid-rodriguez not really, I can reach out to him on Twitter.

**Comment by deivid-rodriguez** [comment]
That would be great! Thanks :)

**Comment by justinfrench** [comment]
Hello!

I'll look at this today 🙂

**Comment by justinfrench** [comment]
Looks good, thanks everyone. Merging now, will do my best to push a gem early tomorrow Melbourne time.

**Comment by justinfrench** [comment]
3.1.5 shipped, thanks everyone!

**Pull request merged**
