### PR TITLE
Improve CI results against rails edge

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
This PR brings rails-edge CI entries closer to green.

There's still two failures, but I think they might be "true positives" (as in, they signal actual problems in formtastic when running against current rails edge, and not just CI setup issues like the ones being fixed here), so I prefer to investigate them separately.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
I confirmed that the two failures don't happen against the latest Rails 6 release, so after this PR adding Rails 6 to the CI should be straightforward :tada:

**Comment by deivid-rodriguez** [comment]
@mikz Pinging you since you merged the last PR? Do you think you'll be able to find some time to review this? Thank you! :purple_heart:

**Comment by mikz** [comment]
Thank you!

**Comment by deivid-rodriguez** [comment]
Thank YOU!!

**Pull request merged**
