### PR TITLE
Add custom input generator support

### PR DESCRIPTION
**Pull request by larrymjordan**

### CODE REVIEW

**Comment by justinfrench** [comment]
Nice. I'm wondering if `--override` and `--extend` could be combined?

```
rails generate formtastic:input foo
rails generate formtastic:input foo --extend string
rails generate formtastic:input string --extend string
rails generate formtastic:input string --extend # assumes it extends class of same name
```

**Comment by larrymjordan** [comment]
@justinfrench Sure, actually that makes it simpler.

**Comment by larrymjordan** [comment]
@justinfrench Done!

**Comment by mikz** [comment]
@larrymjordan looks great!

Does it work with namespaces? Like: 

```
rails generate formtastic:input stuff/foo_input 
rails generate formtastic:input Stuff::FooInput
```

**Comment by larrymjordan** [comment]
@mikz namespaces are not supported yet!. Working on that feature, it looks reasonable.

**Comment by mikz** [comment]
@larrymjordan @justinfrench this looks good :+1:

**Comment by mikz** [comment]
@justinfrench lets merge this? It looks good.

**Comment by justinfrench** [comment]
Sorry for the lag, merging!

**Comment by larrymjordan** [comment]
@justinfrench Nice!

**Comment by rreusser** [comment]
Hmm… looks like this was merged ten months after the most recent release and four months ago. Also looks like this shows up in the github landing page docs though.

Are there plans to release this so that that the latest release matches the docs?

**Comment by rreusser** [comment]
(Sorry, not to be impatient, just trying to avoid confusion for anyone else in case my understanding is correct and the docs are indeed out of sync with the release!)

**Comment by justinfrench** [comment]
@rreusser Sorry, it's been tough for me to keep on top of releases and changes lately. No time, a big 4.0 version underway, and lots of little things that need to be pulled together for a 3.x. @mikz is trying to pull together a new 3.x release at the moment, so it shouldn't be too much longer. Please feel free to nag me again in a month :)

**Pull request merged**
